### ISSUE TITLE
Invalid discovery document

### ISSUE THREAD

**Issue by marklapasa** [okta/okta-sdk-appauth-android#10]
I was able to checkout the code, populate the values in:
..\okta-sdk-appauth-android\app\src\main\res\raw\okta_app_auth_config.json

When I launch the app, my breakpoint lands LoginActivity's mOktaAppAuth.init()'s onTokenFailure(@NonNull AuthorizationException ex)

Inside the AuthorizationException, the errorDescription = "Invalid discovery document"

In detail, it looks like this `AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid discovery document"}`

What do I need to do to get my OktaAppAuth instance initialized?

**Comment by wdawson** [comment]
This could be a problem with the `issuer_uri` value or perhaps with the application configuration within the Okta console. Can you make sure your json document values match the application you've set up?

**Comment by marklapasa** [comment]
This is what I have in my Android project:

![image](https://user-images.githubusercontent.com/4932453/37111573-081353fe-220e-11e8-876b-cd24a67c2c06.png)

This is what is in my Okta console:

![image](https://user-images.githubusercontent.com/4932453/37111772-989d2364-220e-11e8-93b6-b07e8b93c369.png)

**Comment by marklapasa** [comment]
Seems to be working now with the following:

![image](https://user-images.githubusercontent.com/4932453/37113783-681c9926-2214-11e8-8409-b758ec3165d4.png)

**Comment by swagatdishri** [comment]
configuration and json file  both are exactly same,getting the error only in signed apk

**Comment by bdemers** [comment]
@swagatdishri what error are you seeing?
