### ISSUE TITLE
Native flow

### ISSUE THREAD

**Issue by drac94** [okta/okta-sdk-appauth-android#12]
is there a way to do a native flow, I mean to have my own screen to input the email/password and send it to an endpoint to get the token? I've seen that the iOS counterpart of this SDK have implemented that approach but I can't find it here.

Probably not an issue but I didn't know where else to ask.
Thanks.

**Comment by jmelberg-okta** [comment]
Hey @drac94! This flow isn't currently supported by our library. In general, it isn't recommended to use the [Resource Owner Password Flow](https://tools.ietf.org/html/rfc6749#section-1.3.3) in native applications. 

We touched on this a bit in this [forum post](https://devforum.okta.com/t/does-grant-type-authorization-code-always-require-a-manual-intervention-for-providing-username-password/1378/9): 
> I'd recommend using the `sessionToken` flow. This leverages the Okta `sessionToken` to bootstrap your login flow. Essentially:
> 1. Submit user credentials to [`/api/v1/authn`](https://developer.okta.com/docs/api/resources/authn#primary-authentication) to receive a `sessionToken`
> 2. Perform the `/authorize` call using the `sessionToken` and setting the `reponse_type=code`
> 3. Once the `code` is returned, exchange it for an `accessToken` via the `/token` endpoint

We're planning on adding support for this in the future, but in the interm you might need to use the parent SDK [AppAuth-Android](https://github.com/openid/AppAuth-Android) to manually build the `/authorize` and `/token` requests.

**Comment by drac94** [comment]
Thanks so much for the answer @jmelberg-okta, the links you sent me were very useful to give me a clear idea of the approach I will follow for my app.

**Comment by jmelberg-okta** [comment]
Closing this issue as #7 includes a similar feature request.
