### ISSUE TITLE
Use User-Agent header

### ISSUE THREAD

**Issue by robertjd** [okta/okta-sdk-appauth-android#15]
Right now we send "X-Okta-User-Agent", but we should use "User-Agent" to be consistent with other libraries have have the ability to use this header.

**Comment by wdawson** [comment]
@robertjd We should let you set the User-Agent header how you want, but we want to send specific version information to Okta so that we can route to appropriate logic. By using that header, we don't get in the way of the standard or other libraries

**Comment by robertjd** [comment]
Tell me more?  We're trying to standardize on:

`X-Okta-User-Agent-Extended` for front-end libraries (because they cannot set the User-Agent header)

`User-Agent` for everything else

**Comment by wdawson** [comment]
After huddling with some folks, turns out it's like you say. We mistakenly tried to treat our mobile apps as "front end" but shouldn't need to. Let's go ahead with `User-Agent` 🍻
