### ISSUE TITLE
Exception when adding authorization header to request

### ISSUE THREAD

**Issue by vgund9** [okta/okta-sdk-appauth-android#18]
Getting Exception for AuthorizedRequest, 

Exception: 
08-18 20:47:16.902 20347-20419/com.okta.appauth.android.example E/OktaAppAuth: Exception when adding authorization header to request 
java.io.FileNotFoundException: http://XXXX.XXX.XXX.XX:8000/api/data at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:254) at com.okta.appauth.android.OktaAppAuth$9.run(OktaAppAuth.java:624)                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)at java.util.concurrent.FutureTask.run(FutureTask.java:237)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:762)

 
Method:
             

               private void callMessagesApi() {
               Log.i(TAG, "mOktaAppAuth Log :" + mOktaAppAuth);
               mOktaAppAuth.performAuthorizedRequest(new OktaAppAuth.BearerAuthRequest() {
               @NonNull
               @Override
                public HttpURLConnection createRequest() throws Exception {
                 try {
                     final URL myUrl = new URL("http://XXXX.XXX.XXXX.:8000/api/data");
                     HttpURLConnection conn = (HttpURLConnection) myUrl.openConnection();
                     conn.setInstanceFollowRedirects(false); // recommended during authorized calls
                     return conn;
                 } catch (MalformedURLException e) {
                     Log.i(TAG, e.getLocalizedMessage());
                 }
                 return null;
             }

            @Override
            public void onSuccess(@NonNull InputStream inputStream) {
                myDataString=inputStream.toString();
                runOnUiThread(() -> displayAuthorizationInfo());

            }

            @Override
            public void onTokenFailure(@NonNull AuthorizationException e) {
                // Handle failure to acquire new tokens from Okta
            }

            @Override
            public void onFailure(int i, Exception e) {
                // Handle failure to make your authorized request or a response with a 4xx or
                // 5xx HTTP status response code
            }
        });

    }

**Comment by sergiymokiyenko-okta** [comment]
@vgund9 Looks like you connection returns 404 error (that is why you usually get FileNotFound exception). Looks like you are trying to perform "GET" request on "POST" url.
If it is the case than you have to change connection method:
`conn.setRequestMethod("POST");`
