### ISSUE TITLE
OktaAppAuth missing listener call on exceptions

### ISSUE THREAD

**Issue by imbradbrown** [okta/okta-sdk-appauth-android#35]
Could be argued a down stream bug but got into a situation where `OktaAppAuth.refreshAccessToken(OktaAuthListener)` was called even though the user had no refresh token. In other libraries that do these types of guards the listener is still called at some point.

**Comment by nbarbettini** [comment]
Closed via https://github.com/okta/okta-sdk-appauth-android/pull/36
