### ISSUE TITLE
Deprecate LoginHintChangeHandler

### ISSUE THREAD

**Issue by sergiymokiyenko-okta** [okta/okta-sdk-appauth-android#40]
It adds unnecessary complexity for managing login hint. It will be much easier if we can provide login hint as a parameter to `login()` method.

**Comment by wdawson** [comment]
At the same time, can we maintain the ability to ensure that we don't constantly reload the browser as the user types?

**Comment by nbarbettini** [comment]
> At the same time, can we maintain the ability to ensure that we don't constantly reload the browser as the user types?

@wdawson Is that a current bug? Something you've seen in the past?

**Comment by smokienko** [comment]
@wdawson I want to simplify flow and skip the process of updating browser in the background at all.

**Comment by wdawson** [comment]
Fine if we can remove it and maintain the user experience (no, or shorter loading screen). 

The current implementation tries to balance performance and user experience. It is more complicated for the developer though. I had tried to make it pretty clear through documentation and examples what to do, though. 

Anyway, I don't have strong opinions. Just want to make sure you're both aware of the intention of the current implementation @nbarbettini @smokienko

**Comment by nbarbettini** [comment]
@smokienko I agree, we can skip updating the browser in the background. It is nice to have the browser ready a little sooner, but it makes it harder to understand the code.

Let's deprecate this (don't remove it yet, save that for the next major version), and replace it with #41.
