### ISSUE TITLE
Update note

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-appauth-android#5]
This part of the readme is extraneous:

> Note: As with any Okta application, make sure you assign Users or Groups to the application. Otherwise, no one can use it.

The Add Application wizard automatically adds the Everyone group to new applications, so it's not something a first-time dev needs to worry about. We should either:

* Update the note to mention that this is already done for you 👍 
* Remove the note

**Comment by jmelberg-okta** [comment]
Merged via #6
