### ISSUE TITLE
Create samples repo

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-appauth-android#50]
I've created this repo as a place for official Android samples: https://github.com/okta/samples-android

It will be modeled similar to: https://github.com/okta/samples-js-angular

- [ ] Create readme
- [ ] Create folder `browser-signin`
- [ ] Create folder `native-signin` (this will contain #39)

**Comment by jordiJIG** [comment]
Hi,

Samples url throws a 404.....

Thanks!!
