### ISSUE TITLE
Sample Project Not building - Missing Dependency, Old Google libraries used

### ISSUE THREAD

**Issue by anoop-xrx** [okta/okta-sdk-appauth-android#55]
Steps to recreate the issue:

1. clone the repo using `git clone https://github.com/okta/okta-sdk-appauth-android.git`
2. Open the project in Android Studio 3.2.1
3. Clean and Build the project
4. The issues are appearing with respect to missing classes in, `net.openid.appauth` package. Attached error.txt file having all the details. the library module completely fails to compile.
[error.txt](https://github.com/okta/okta-sdk-appauth-android/files/2726207/error.txt)

I doubt weather this sample is in runnable state for devs to test a basic implementation. 

Why is old google libraries used? With the new compileSDK and targetSDK updates and requirements using 27.1.1 is not a good idea.

Screenshot:
![error_okta](https://user-images.githubusercontent.com/46367035/50677121-0de9cc00-101e-11e9-9511-0b8a1d66418f.png)

**Comment by bdemers** [comment]
@anoop-xrx did you init the submodules too?

**Comment by anoop-xrx** [comment]
@bdemers I cloned the project. The directory **`app-auth`** is empty. However the directory points to another repo in github pages (https://github.com/okta/okta-sdk-appauth-android/tree/master/app-auth).

Should I add these manually?

**Comment by bdemers** [comment]
@anoop-xrx sounds like you worked updated the submodules and have things building!

I'm going to close this issue and we can keep the thread in #56
