### ISSUE TITLE
Using the okta library as a dependency in gradle - Causes build to fail

### ISSUE THREAD

**Issue by anoop-xrx** [okta/okta-sdk-appauth-android#56]
Steps to recreate the issue:
1. Create a new Sample Project in Android studio 3.2.1. with minSDK 19 and targetSDK 28 with an empty activity.
2. The app will compile and run at this stage.
3. Add `implementation 'com.okta.android:appauth-android:0.1.0'` in app module's build.gradle
4. Will get an error under the appcompact library stating multiple play service modules issue.

Please see the screenshot attached below.
![error_okta2](https://user-images.githubusercontent.com/46367035/50679204-7d64b900-1028-11e9-970f-8033375a5bab.png)

**Comment by bdemers** [comment]
@anoop-xrx 

Did you add the corresponding redirect scheme to your build.gradle similar to:
https://github.com/okta/okta-sdk-appauth-android/blob/master/app/build.gradle#L13-L15

**Comment by anoop-xrx** [comment]
@bdemers Yes I did add. I am able to compile now. But the library error still exists. I assume that the OKTA library uses outdated google library.

**Comment by bdemers** [comment]
@anoop-xrx I changed the title back to the original so track the issues you are having independently 

I've also created another issue to track the build warnings: #58
