### ISSUE TITLE
Ending Session/ Logout section of readme is not correct

### ISSUE THREAD

**Issue by anoop-xrx** [okta/okta-sdk-appauth-android#64]
> End session
> 
> In order to perform end session within user's current browser and perform logout you have to call signOutFromOkta() whenever you are ready
> 
> // LoginActivity.java
> 
> public class UserInfoActivity extends Activity {
> 
>     private void signOutFromOkta() {
>         Intent completionIntent = new Intent(this, LoginActivity.class);
>         Intent cancelIntent = new Intent(this, UserInfoActivity.class);
>         cancelIntent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
> 
>         mOktaAuth.endSession(
>                 this,
>                 PendingIntent.getActivity(this, 0, completionIntent, 0),
>                 PendingIntent.getActivity(this, 0, cancelIntent, 0)
>         );
>     }
> }

The Read me containing the information on end session is showing an outdated code snippet. Currently the logout is the only method. mOktaAuth.logout();

**Comment by smokienko** [comment]
@anoop-xrx it should be working from v 0.2.0, but we have also renamed `endSession` to `signOutFromOkta`. We are going to push this small changes to readme today, thanks for pointing out!
