### ISSUE TITLE
Conflict with 2 differents apps

### ISSUE THREAD

**Issue by jmarchand1** [okta/okta-sdk-appauth-android#87]
Hi,
I haved created and installed 2 different apps based on okta-sdk-appauth-android git.
I have a conflit between these 2 apps installed when I finish to authenticate with the chrome browser.
In the chrome browser, after a clic on log in button. I have to choose between the 2 installed applications to finish the action.

How can i use a different browser  instance in each app?

Thank you.

**Comment by Fei-Chen-** [comment]
You have to create a separate application in the okta admin dashboard to separate the schema.
In your case it sounds like both apps are registered using the same schema. If both apps use the same appAuthRedirectScheme then Android will ask the user to select an app to handle the redirect.

**Comment by jmarchand1** [comment]
Thank you  for your answer.

My 2 applications are 2 separated application with 2 different client id .
For one of them the "Login redirect Uri " is equal to com.oktapreview.dev-xxxxxx:/callbackNative
the second on is equal to com.oktapreview.dev-xxxxxx:/callback.

com.oktapreview.dev-xxxxxx is identical for the 2 apps.

How can i change com.oktapreview.dev-xxxxxx?
Do I have to change xxxxxx value?
Do I have to create another admin account which will generate an other account number ?

Thank you

**Comment by Fei-Chen-** [comment]
You can use the package name of your application not the okta account domain.

{package name}:/callback
{package name}:/callbackNative

For example:
com.okta.appauth.android.example:/callback
com.okta.appauth.android.example.second:/callbackNative

in the app gradle file:
```
        manifestPlaceholders = [
                "appAuthRedirectScheme": "com.okta.appauth.android.example"
        ]
```

Make sure to add these in the admin dashboard for Login redirect URIs for both apps. They should use the apps package like the following:

![screen shot 2019-02-20 at 9 06 20 am](https://user-images.githubusercontent.com/7664769/53109955-dca25e00-34ee-11e9-9192-72ef0ca62995.png)

**Comment by jmarchand1** [comment]
Thank you for your answer.

It works.

Thank you.

**Comment by FeiChen-okta** [comment]
You're welcome.
